name: CI – Build & Test

# Se dispara en push y PR sobre la rama main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonamos el repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Instalamos Node.js 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Instalación determinista
      - name: Install dependencies
        run: npm ci

      # 4) Ejecutar tests
      - name: Run tests
        run: npm test
